### ISSUE TITLE
 Cache2k in OSGI when calling to getAll(Keys)

### ISSUE THREAD

**Issue by panarch81** [cache2k/cache2k#100] opened 2019-01-28 19:51 UTC
Hi repo owners! I need some help to use cache2k in OSGI ... We are trying to manage multiple keys using the Read Through strategy of cache2k, trying to use getAll and implementing loadAll method inside the loader, but in runtime, is always calling to load(String key)  method, and never to loadAll(Iterable<> keys). May you consider this soon or do you have already some other solution?
In other hand, we know there's an implementation of jcache's specification for getAll(keys), but we couldn't find the bundle for osgi. Is there any osgi bundle or something coming soon? thank you!

**Comment by cruftex** [comment] 2019-01-29 08:52
> is always calling to load(String key) method, and never to loadAll(Iterable<> keys). 

The method comment on `loadAll()` reads:

> The method is provided to complete the API. At the moment cache2k is not using it. Please see the road map.

Using `loadAll` would be a performance improvement if you do a lot bulk requests. 

> May you consider this soon or do you have already some other solution?

The loader needs to always implement a `load` method, so you code should work without `loadAll` usage. At the moment our applications would not benefit much from using `loadAll` as well, so that's why its not yet used. Maybe it will be used by future versions when there is more demand for it.

If you like you can explain your usage scenario, so maybe I can make alternative suggestions.

> I need some help to use cache2k in OSGI 

That behavior is not related to OSGi, but in cache2k in general.

Closing since the issue is answered. However, I am happy to discuss your scenario more, so feel free to comment.

**Closed by cruftex** 2019-01-29 08:52 UTC

**Comment by panarch81** [comment] 2019-01-29 14:21
Hi again, 
We would like to use loadAll() to call with many keys in a single http request, and not N requests using load() method.
Thank you!
