### ISSUE TITLE
ServiceConfigurationError in Android

### ISSUE THREAD

**Issue by dave08** [cache2k/cache2k#137] opened 2020-02-02 14:06 UTC
I get this exception every other build...
``` 
   java.util.ServiceConfigurationError: Couldn't read jar:file:/data/app/....-1/base.apk!/META-INF/services/org.cache2k.spi.Cache2kCoreProvider
        at java.util.ServiceLoader$ServiceIterator.readClass(ServiceLoader.java:245)
        at java.util.ServiceLoader$ServiceIterator.hasNext(ServiceLoader.java:202)
        at org.cache2k.spi.b.a(SingleProviderResolver.java:106)
        at org.cache2k.spi.b.a(SingleProviderResolver.java:82)
        at org.cache2k.spi.b.b(SingleProviderResolver.java:64)
        at org.cache2k.f.<clinit>(CacheManager.java:54)
        at org.cache2k.c.b(Cache2kBuilder.java:160)
```

the first build crashes the app with that exception, the second one succeeds. I'm using r8 with the Proguard rules that are on the cache2k.org docs.

**Comment by cruftex** [comment] 2020-02-03 12:49
Since we are not doing much Android development ourselves, I did not make any tests with R8.
Can you provide a tiny project that reproduces the problem?

> the first build crashes the app with that exception, the second one succeeds.

What do you mean by: "the build crashes the app"?

**Comment by dave08** [comment] 2020-02-03 13:27
Basically, every time we make changes to the codebase, I run the gradle build/install, the first time the apk is installed it crashes with the previous error, the next time I build/install, it works. So for every change we need to compile/install twice...

**Comment by cruftex** [comment] 2020-02-03 14:26
@dave08: The stacktrace is generated from running a program with cache2k. Its unclear to me in what situation and environment this happens during your "build/install" and why.

**Comment by dave08** [comment] 2020-02-03 14:32
r8 already complained with the current Proguard rules... I needed to change this:
```
-keep public class * extends org.cache2k.spi.Cache2kCoreProvider
...
-keep public class * extends org.cache2k.core.spi.CacheConfigurationProvider
-keepclassmembers public class * extends org.cache2k.configuration.ConfigurationBean {
```

to this:

```
-keep public class * implements org.cache2k.spi.Cache2kCoreProvider
...
-keep public class * implements org.cache2k.core.spi.CacheConfigurationProvider
-keepclassmembers public class * implements org.cache2k.configuration.ConfigurationBean {
```
otherwise it gave me errors... could this change have caused the problem? Or maybe the library changed ever since the rules were authored?

**Comment by dave08** [comment] 2020-02-03 16:33
In the end, we discovered that the problem is only in Lollipop... from Marshmallow it seems to work well. Is there anything to do, or is Lollipop not supported?

**Comment by cruftex** [comment] 2020-02-03 16:56
Interesting, thanks for the update!

I am still automatically testing with Android 4.1 Jelly Bean (API 16). So theoretically, everything above should work.

There was trouble with Android in the past and its always class loading around the SPI mechanism.
SPI is used in cache2k to have the option to ship different implementations for the same API. However, there is only a single implementation right now. Maybe I should remove or simplify that area.

**Comment by cruftex** [comment] 2020-08-14 01:05
Closing. We need to start working on cache2k version 2 and drop support of older Android version anyway. Its unclear whether and how we will support Android anyways in the future, since we don't have capacity for validation tests at the moment.
I opened https://github.com/cache2k/cache2k/issues/143 to further address this.

**Closed by cruftex** 2020-08-14 01:05 UTC
Labels: bug
