### ISSUE TITLE
Add note to documentation when using Spring integration and Optional values

### ISSUE THREAD

**Issue by alfonsomunozpomer** [cache2k/cache2k#141] opened 2020-08-09 13:08 UTC
The [chapter on null values](https://github.com/cache2k/cache2k/blob/master/documentation/src/docs/asciidoc/user-guide/sections/_null.adoc) states that:
> In case the loader returns `null` and this should not lead to an exception the following options exist:
> Always return a non-null object and include a predicate for the `null` case, use a list or Java 8 `Optional`.

However, when using the Spring Framework integration and values are of class `Optional`, since [Spring unwraps the value in `CacheAspectSupport`](https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/main/java/org/springframework/cache/interceptor/CacheAspectSupport.java#L451), an NPE will be thrown unless `permitNullValues` is set to `true`.

I think this is worth mentioning in [the Spring chapter](https://github.com/cache2k/cache2k/blob/master/documentation/src/docs/asciidoc/user-guide/sections/_spring.adoc). Let me know what you think. I can open a PR to add this to the docs. I haven’t done so because I don’t know if https://github.com/cache2k/cache2k/issues/135 will conflict with Spring or will make that consideration unnecessary.

**Comment by cruftex** [comment] 2020-08-10 00:32
@alfonsomunozpomer thanks for pointing that out. That feels more like a bug to me!

The Spring support uses the feature of cache2k to store `null` values natively. Most of the other caches store the wrapper as value. I opted not to do so, to avoid the additional memory overhead. On the downside, values need wrapping each time the cache is accessed to adapt the Springs' interface.

It seems the best/correct solution is always to enable `permitNullValues` in the spring cache manager. What do you think?

**Comment by alfonsomunozpomer** [comment] 2020-08-10 09:28
It makes sense. The `permitNullValues`, though, will still be visible and could be set to `false`? In that case I guess it’s worth mentioning it in the documentationas a possible optimisation/pitfall.

Out of curiosity, does the unwrapping become noticeable on aggregate when the hit ratio is high?

**Comment by alfonsomunozpomer** [comment] 2020-08-10 10:50
Also, while reading [Spring’s documentation](https://docs.spring.io/spring/docs/5.1.5.RELEASE/spring-framework-reference), I saw the following in [the conditional caching section](https://docs.spring.io/spring/docs/5.1.5.RELEASE/spring-framework-reference/integration.html#cache-annotations-cacheable-condition):
> The cache abstraction supports `java.util.Optional`, using its content as the cached value only if it is present. `#result` always refers to the business entity and never a supported wrapper

So maybe it’s better to cache `unless="#result==null"` or maybe `unless="#result"`, or whatever it should be written in SpEL. I should try this out, though.

**Comment by cruftex** [comment] 2020-08-11 01:29
@alfonsomunozpomer 

Just realizing that I actually documented it already:

**Null Value Support**
The cache abstraction of Spring is supporting null values. If the application relies on null storage this has to be enabled via `Cache2kBuilder.permitNullValues(true)`, see Null Values.

However, that is not ideal. A Spring application should just work without any extra special configuration when using cache2k.
So I make this default in Spring now. Probably my reasoning against doing that, was not to have different configuration defaults in cache2k within different contexts.

>  The `permitNullValues`, though, will still be visible and could be set to false?

Yes. I don't see that this is a problem. It actually makes sense. If a cache is not meant to store `null` values, this can
be disabled again in the configuration. This is an important property to know, so its good to have a parameter that
documents and enforces it.

**Comment by alfonsomunozpomer** [comment] 2020-08-11 14:37
What I found confusing is that, even though Sprint supports `null` values, an empty `Optional` is unwrapped to `null`. The only documentation of such behaviour is a foot note in the conditional caching section, which I missed, and discovered by debugging Spring libraries. 

So in Spring `permitNullValues(false)` would be an optimisation of sorts?

**Comment by cruftex** [comment] 2020-08-25 05:13
@alfonsomunozpomer I released version 1.3.4.Beta with `permitNullValues(true)` within the Spring support module.
I also pushed some test code for null support, see:
https://github.com/cache2k/cache2k-qa/commit/03fe7fa213904bc02c0e7b77e262d9a627e672d1

Please: I am not sure whether this addresses the actual problem you reported. Can you please check and
provide some code for reproduction if there is still a problem?

**Comment by cruftex** [comment] 2020-08-25 05:27
> So in Spring permitNullValues(false) would be an optimisation of sorts?

Using `permitNullValues(true)` and using the null support in cache2k is the optimization for Spring, because that means there is no additional object wrapper needed.

Just looking on cache2k itself there is no runtime difference whether this is enabled or not. The flag is present to be aware of the difference in behavior. Historically null support was always enabled. But analyzing code using the cache revealed that developers think that `null` means no cached value is present. Typical cache aside code looked like:

```
  V value = cache.get(key);
  if (value == null) {
    value = ....;
    cache.put(key, value);
  }
```

As soon `null` is a legal value in the cache, that code is wrong.

**Comment by alfonsomunozpomer** [comment] 2020-08-25 11:00
Thanks for the lengthy explanation. Makes sense. I’ll test 1.3.4.Beta next week and I’ll let you know. At the moment I’m initialising the caches with `Optional` values with `permitNullValues(true)`, so it’ll mean some less boilerplate, I guess.

**Comment by cruftex** [comment] 2020-09-12 02:00
Releasing 1.4 and closing this issue, in the hope that nothing is left to do. Please feel free any time to comment here or raise another issue if there is still a problem.

**Closed by cruftex** 2020-09-12 02:00 UTC
Labels: bug
