### ISSUE TITLE
Resources is not cleanup after CacheManager::close

### ISSUE THREAD

**Issue by quaff** [cache2k/cache2k#168] opened 2020-12-28 07:26 UTC
Tested with v2.0.0, after `CacheManager::close` call finished, there is a thread[ForkJoinPool.commonPool-worker-n] created by cache2k remain alive for a few seconds, tomcat report such warning on shutdown.
It seems `HeapCache::cancelTimerJobs` will not terminate timer thread immediately.

**Comment by cruftex** [comment] 2020-12-28 07:47
@quaff I did some work about this in #167. A timer thread would be named `cache2k-scheduler`. The thread you are referring is from the common executor.  Cache2k uses that for async operations, e.g. for async listeners, or, if your are using an async loader and `loadAll`.

Can you do a thread dump with stacktraces, to see what is executing there?

**Comment by cruftex** [comment] 2020-12-28 07:53
To fix this `close` would probably need to wait until all processing is finished. That's something I would like to avoid. E.g. a thread could execute a load which might take quite a long time.

**Comment by quaff** [comment] 2020-12-28 07:54
here is tomcat warning:
```
28-Dec-2020 15:51:15.363 WARNING [Thread-4] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [ForkJoinPool.commonPool-worker-9] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1835)
 java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1704)
 java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
28-Dec-2020 15:51:15.369 INFO [Thread-4] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["http-nio-8080"]
28-Dec-2020 15:51:15.374 INFO [Thread-4] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["http-nio-8080"]

```
I don't think it caused by `cache2k-scheduler`, If I add breakpoint suspend `Thread-4` to wait for `ForkJoinPool.commonPool-worker-9` termination, the warning is gone.

**Comment by quaff** [comment] 2020-12-28 07:59
> To fix this `close` would probably need to wait until all processing is finished. That's something I would like to avoid. E.g. a thread could execute a load which might take quite a long time.

It make sense to interrupt pending processing, then wait for an acceptable duration.

**Comment by cruftex** [comment] 2020-12-28 08:29
> It make sense to interrupt pending processing, then wait for an acceptable duration.

That produces overhead. Not sure whether this should be the standard. Maybe it should, because cache2k tries to be "easy" for developers. Maybe it should not, because there is no real good choice. The usage of executors depend on the particular technical environment and application behavior.

The actual warning seems to appear, because the `ForkJoinPool` thread has not timed out yet. It is actually not a real problem.

You can specify your own executor and then do `shutdownNow` after all caches are closed using that executor/executorservice.
Since version 2.0 the configured executor may implement  `AutoCloseable` and `close` gets called when the cache is closed.
You can also configure an executor factory, aka `CustomizationSupplier`, which could than give each cache a separate executor or a wrapped executor which keeps track of the tasks currently in flight. So the behavior can be adapted to fit for your environment.

However, in this case, I think Tomcat should ignore it. If your application uses `CompletableFuture` most likely the common pool would be used and create threads as well. There are others that have the same problem:
https://backstage.forgerock.com/knowledge/kb/article/a55893580

**Comment by cruftex** [comment] 2020-12-28 08:33
@quaff: Are you using the Spring integration of cache2k or directly or maybe JCache?

**Comment by quaff** [comment] 2020-12-29 00:23
> > It make sense to interrupt pending processing, then wait for an acceptable duration.
> 
> That produces overhead. Not sure whether this should be the standard. Maybe it should, because cache2k tries to be "easy" for developers. Maybe it should not, because there is no real good choice. The usage of executors depends on the particular technical environment and application behavior.
> 
> The actual warning seems to appear, because the `ForkJoinPool` thread has not timed out yet. It is actually not a real problem.
> 
> You can specify your own executor and then do `shutdownNow` after all caches are closed that use that executor/executorservice. Since version 2.0 the configured executor may implement `AutoCloseable` and `close` gets called when the cache is closed. You can also configure an executor factory, aka `CustomizationSupplier`, which could than give each cache a separate executor or a wrapped executor which keeps track of the tasks currently in flight. So the behavior can be adapted to fit for your environment.
> 
> However, in this case, I think Tomcat should ignore it. If your application uses `CompletableFuture` most likely the common pool would be used and create threads as well. There are others that have the same problem:
> https://backstage.forgerock.com/knowledge/kb/article/a55893580

I tried passing `executor` and `scheduler`, It doesn't work, `HeapCache. SHARED_EXECUTOR` is final.
https://github.com/cache2k/cache2k/blob/2706bc8d6e700e74c470b7f8b3d694be64265578/cache2k-core/src/main/java/org/cache2k/core/HeapCache.java#L304

**Comment by quaff** [comment] 2020-12-29 00:25
> @quaff: Are you using the Spring integration of cache2k or directly or maybe JCache?

directly, like this:
```java
@Component("cacheManager")
public class Cache2kCacheManager{

	private static final AtomicInteger INSTANCE_NUMBER = new AtomicInteger();

	private org.cache2k.CacheManager cache2kCacheManager;

	@PostConstruct
	public void init() {
		int number = INSTANCE_NUMBER.getAndIncrement();
		String name = number > 0 ? "ironrhino" + number : "ironrhino";
		cache2kCacheManager = org.cache2k.CacheManager.getInstance(name);
	}

	@PreDestroy
	public void destroy() {
		cache2kCacheManager.close();
	}

	@Override
	public void put(String key, Object value, int timeToLive, TimeUnit timeUnit, String namespace) {
		if (key == null)
			throw new IllegalArgumentException("key should not be null");
		if (value == null)
			throw new IllegalArgumentException("value should not be null");
		Cache<String, Object> cache = getCache(namespace, true);
		cache.invoke(key, entry -> entry.setValue(value).setExpiryTime(timeToLive == 0 ? ExpiryTimeValues.ETERNAL
				: (System.currentTimeMillis() + timeUnit.toMillis(timeToLive))));
	}



	@Override
	public Object get(String key, String namespace) {
		if (key == null)
			throw new IllegalArgumentException("key should not be null");
		Cache<String, Object> cache = getCache(namespace, false);
		if (cache == null)
			return null;
		return cache.get(key);
	}

	...

	private Cache<String, Object> getCache(String namespace, boolean create) {
		if (StringUtils.isBlank(namespace))
			namespace = "_default";
		namespace = namespace.replaceAll(":", ".");
		Cache<String, Object> cache = cache2kCacheManager.getCache(namespace);
		if (cache != null)
			return cache;
		if (create) {
			synchronized (this) {
				cache = cache2kCacheManager.getCache(namespace);
				if (cache == null) {
					cache = cache2kCacheManager.createCache(Cache2kBuilder.of(String.class, Object.class)
							.name(namespace).expireAfterWrite(1, TimeUnit.HOURS).entryCapacity(10000)
							.timerLag(10, TimeUnit.MILLISECONDS).config());
				}
			}
		}
		return cache;
	}

}

```

**Comment by cruftex** [comment] 2020-12-29 00:30
> I tried passing executor and scheduler, It doesn't work, HeapCache. SHARED_EXECUTOR is final.

That's only used as fallback, when nothing is specified. I admit the code is not very readable. Will improve that.
How do you detect that it did not work? The effect you are experiencing might not be caused by cache2k but from some unrelated `CompletableFuture` usage or other parts Java that use the common pool.

**Comment by quaff** [comment] 2020-12-29 00:34
> > I tried passing executor and scheduler, It doesn't work, HeapCache. SHARED_EXECUTOR is final.
> 
> That's only used as fallback, when nothing is specified. I admit the code is not very readable. Will improve that.
> How do you detect that it did not work? The effect you are experiencing might not be caused by cache2k but from some unrelated `CompletableFuture` usage or other parts Java that use the common pool.

I'm pretty sure it caused by cache2k, the warning doesn't show if no cache interaction.

**Comment by cruftex** [comment] 2020-12-29 01:41
Looking at your code that is probably from the expiry that you use. So let's amend my previous comment about the timer/scheduler: Since the new scheduler / expiry code in version 1.6 cache2k uses the executor to process timer events rather than to execute timer events within the timer threads. This is intended to leverage increase parallelism and use available cores and to prevent a bottleneck when there are large caches and/or expiry happening at the same time. This uses the common `ForkJoinPool` as executor if nothing else is specified. There are other uses in cache2k of the common pool as well, e.g. for async and event processing. 

However, if cache2k would wait until all processing in the executor is finished, the common pool would still keep the thread for a while and Tomcat will print the warning. So Tomcat prints a warning when an application uses JVM resources as they are intended to be used. That's worth fixing in Tomcat. Can you open an issue there?

In regards to tasks pending or in flight, I don't see a general good approach for an orderly shutdown. Should we ignore, 
cancel or wait? I don't see a general usable way to deal with pending tasks. That depends on the application and the environment. E.g. for some applications it might be okay to cancel a modification event listener task, for others it might not.
To adapt to the requirements cache2k allows to specify separate executors that are used in various occasions.

If setting an alternative executor has no effect, then this is a bug in cache2k. That's a separate issue then.

**Comment by cruftex** [comment] 2020-12-29 01:48
> If setting an alternative executor has no effect, then this is a bug in cache2k. That's a separate issue then.

Oh wait, I just double checked. The scheduler uses always the common pool and the `executor()` has no effect at the moment as you said. Sorry about that. The relevant code is in `DefaultSchedulerProvider`. The behavior could be changed by configuring in another scheduler, which is possible as well.

Probably its a good idea to use the configured executor here. In the design I expected that people typically would replace the scheduler, but your example shows that we should be able to change the executor alone.

**Comment by quaff** [comment] 2020-12-29 01:50
> Looking at your code that is probably from the expiry that you use. So let's amend my previous comment about the timer/scheduler: Since the new scheduler / expiry code in version 1.6 cache2k uses the executor to process timer events rather than to execute timer events within the timer threads. This is intended to leverage increase parallelism and use available cores and to prevent a bottleneck when there are large caches and/or expiry happening at the same time. This uses the common `ForkJoinPool` as executor if nothing else is specified. There are other uses in cache2k of the common pool as well, e.g. for async and event processing.
> 
> However, if cache2k would wait until all processing in the executor is finished, the common pool would still keep the thread for a while and Tomcat will print the warning. So Tomcat prints a warning when an application uses JVM resources as they are intended to be used. That's worth fixing in Tomcat. Can you open an issue there?
> 
> In regards to tasks pending or in flight, I don't see a general good approach for an orderly shutdown. Should we ignore,
> cancel or wait? I don't see a general usable way to deal with pending tasks. That depends on the application and the environment. E.g. for some applications it might be okay to cancel a modification event listener task, for others it might not.
> To adapt to the requirements cache2k allows to specify separate executors that are used in various occasions.
> 
> If setting an alternative executor has no effect, then this is a bug in cache2k. That's a separate issue then.

I'd prefer to set my own executor and shutdown when destroy bean, graceful shutdown is very important for me.

**Comment by quaff** [comment] 2020-12-29 01:53
> > If setting an alternative executor has no effect, then this is a bug in cache2k. That's a separate issue then.
> 
> Oh wait, I just double checked. The scheduler uses always the common pool and the `Cache2kBuilder.executor()` configuration has no effect at the moment as you said. Sorry about that. The relevant code is in `DefaultSchedulerProvider`. The behavior could be changed by configuring in another scheduler, which is possible as well.
> 
> Probably its a good idea to use the configured executor here. In the design I expected that people typically would replace the scheduler, but your example shows that we should be able to change the executor alone.

As I said, I tried configuring both `executor` and `scheduler`, but it doesn't works, cache2k  is not using them at somewhere.

**Comment by cruftex** [comment] 2020-12-29 01:53
> I'd prefer to set my own executor and shutdown when destroy bean, graceful shutdown is very important for me.

I agree. See my other comment just now.

**Comment by cruftex** [comment] 2020-12-29 02:05
Okay I opened a more specific issue for that:
https://github.com/cache2k/cache2k/issues/169

I suggest we close this one, since we now know how to address this.

**Closed** 2020-12-29 02:07 UTC
