### ISSUE TITLE
Fixed-time caching, caches forever!

### ISSUE THREAD

**Issue by mohsen** [cache2k/cache2k#20] opened 2015-06-09 16:41 UTC
Hi,
I used to use Google guava cache for fixed-time caching of certain contents on a web application. After knowing about cache2k, I wrote a small facade to be able to switch between cache2k and guava, and changed my default cache framework to cache2k on a high traffic website (~100k unique users per day). I switched to cache2k for two reasons.
First it's out of the box JMX support.
Second I assumed that when my DB fails for any reason, and so ``org.cache2k.CacheSource.get(K)`` throws any exception, cache2k continues to return old cached values for the keys. So my website home page would continue to work even after DB gets down.

I was satisfied with JMX support but about the second I was wrong. Please tell me if this is intended behavior that cache fails when CacheSource.get() fails.

Well, this post is about another issue which seems to be very severe:
The problem is about fixed-time caching and *strong* caching of cache2k. In my high traffic website fixed-time caching never refreshed after a couple of days, that is, it kept old values and did not update values every 1 minute (1 minute was my fixed caching period). The case was getting bad when I added an API to do a ``org.cache2k.Cache.remove(K)`` for failed caches so that website admin can refresh a cache himself. It works for some days but again fails after that. and Cache.remove(K) did nothing.

Switching back to guava, everything works fine.

**Comment by cruftex** [comment] 2015-06-09 22:17
> Second I assumed that when my DB fails for any reason, and so org.cache2k.CacheSource.get(K) throws any exception, cache2k continues to return old cached values for the keys. So my website home page would continue to work even after DB gets down.

This behaviour is the default. It can be controlled, turned off, with CacheBuilder.suppressExceptions()

Either your problem is a bug or some of your setup parameters interfere with each other. Can you please provide me the parameters how you construct the Cache?

**Comment by mohsen** [comment] 2015-06-10 02:54
Well I was wrong about supressingException. It works fine at least in my test case. Website becomes very slow when DB shuts down, but it's nothing with cache2k but JDBC pooling internals.

About eviction issue, I cannot reproduce it because it only happens on my high traffic website, and also once (last week) on a low traffic website. Here is the way I construct a cache2k:

    private <K, V> Cache<K, V> buildCache2k(String cacheName, Class<K> keyClass, Class<V> valueClass, final Loader<K, V> loader,
            Integer expireAfterSeconds, TimeUnit timeUnit, int maxSize) {
        org.cache2k.CacheBuilder<K, V> c = org.cache2k.CacheBuilder.newCache(keyClass, valueClass).maxSize(maxSize)
                .source(new CacheSource<K, V>() {
                    @Override
                    public V get(K k) throws Throwable {
                        return loader.load(k);
                    }
                });
        if (expireAfterSeconds != null) {
            c.expiryDuration(expireAfterSeconds, timeUnit);
        }
        c.name(cacheName);
        return c.build();
    }

**Comment by cruftex** [comment] 2015-06-11 18:02
You setup looks good to me.

If you have a higher latency from your DB pool which lead to the exceptions, you could try with backgroundRefresh(true). What happens, is that the Cache keeps busy trying refreshing the entries, but your application will not stall. What is missing for backgroundRefresh, that the number of used threads is controllable. Currently for all caches the same thread pool is used with the number of threads being 2 * available CPUs. I think, it should be possible to configure it per Cache instance.

Expiry: Can you please check you exceptions log, just before it happened? Maybe something stopped the expiry handling thread. 

If you do another test, it would help to have a log output of Cache.toString() e.g. every 10 minutes. This way we know about the inner state of the cache.

We use exactly the same cache version in a high traffic website, too. I don't have any doubt that we get this sorted out and working for you.

**Comment by mohsen** [comment] 2015-06-12 07:54
Thanks for letting me know about ``backgroundRefresh(boolean)``. It's a very valuable API for my website. Together with ``exceptionExpiryDuration(long, TimeUnit)`` I can keep my website up and working. As you mentioned, currently number of threads in ``org.cache2k.impl.CacheRefreshThreadPool`` is not enough. I suggest to make number of threads controllable and per cache instance. In a website behind tomcat with 500 threads, background refresh threads would consume in less than a few seconds.

About possible bug, I will try again with cache2k in my real application. Will enable logging every 10 minutes, and report here if bug raised again.

**Comment by mohsen** [comment] 2015-06-13 07:38
Today I enabled cache2k on my website and the eternal caching issue happened again. Here is details:
* cache name: newsArchiveCache
* cache size: 1000 (which should be larger but I have memory constraints here)
* expiry duration: 1 minute

Last time cache is refreshed at 10:12:14 for a certain key (below) and not refreshed again until I stopped server and reverted to guava. Although the page under which cache is used is requested a lot, cache2k returns same data.

Here is my log at the end of load() method which is called from ``org.cache2k.CacheSource.get(K)``:

```2015-06-13 10:12:14,655 INFO <> News archive cache reloaded for NewsArchiveCacheKey[topicId=1, from=Sat Jun 13 00:00:00 IRDT 2015, to=Sat Jun 13 23:59:59 IRDT 2015, firstResult=0, pageSize=30, sort=null], took 29ms```

Here is the cache.toString() every 10 minutes:
```
2015-06-13 09:12:52,097 INFO <> [cache2k] Cache{newsArchiveCache}(size=1000, maxSize=1000, usageCnt=8246, missCnt=2691, fetchCnt=5584, fetchButHitCnt=3351, heapHitCnt=6013, virginEvictCnt=0, fetchesInFlightCnt=0, newEntryCnt=2233, bulkGetCnt=0, refreshCnt=2893, refreshSubmitFailedCnt=30, refreshHitCnt=710, putCnt=0, putNewEntryCnt=0, expiredCnt=2639, evictedCnt=1233, removedCnt=0, storageLoadCnt=0, storageMissCnt=0, storageHitCnt=0, hitRate=67.36%, collisionCnt=201, collisionSlotCnt=171, longestCollisionSize=5, hashQuality=83, msecs/fetch=102.33506446991404, created=2015-06-13 07:32:33.12, cleared=-, touched=2015-06-13 09:12:50.199, fetchExceptionCnt=2938, suppressedExceptionCnt=2900, internalExceptionCnt=0, keyMutationCnt=0, infoCreated=2015-06-13 09:12:52.097, infoCreationDeltaMs=0, impl="LruCache", integrityState=0.9.4f79b249)
2015-06-13 09:22:53,373 INFO <> [cache2k] Cache{newsArchiveCache}(size=1000, maxSize=1000, usageCnt=8694, missCnt=3010, fetchCnt=6235, fetchButHitCnt=3744, heapHitCnt=6203, virginEvictCnt=0, fetchesInFlightCnt=0, newEntryCnt=2491, bulkGetCnt=0, refreshCnt=3225, refreshSubmitFailedCnt=30, refreshHitCnt=802, putCnt=0, putNewEntryCnt=0, expiredCnt=2933, evictedCnt=1491, removedCnt=0, storageLoadCnt=0, storageMissCnt=0, storageHitCnt=0, hitRate=65.37%, collisionCnt=208, collisionSlotCnt=184, longestCollisionSize=4, hashQuality=88, msecs/fetch=94.83319967923015, created=2015-06-13 07:32:33.12, cleared=-, touched=2015-06-13 09:22:50.05, fetchExceptionCnt=3270, suppressedExceptionCnt=3232, internalExceptionCnt=0, keyMutationCnt=0, infoCreated=2015-06-13 09:22:53.373, infoCreationDeltaMs=0, impl="LruCache", integrityState=0.9.4f79b249)
2015-06-13 09:32:53,376 INFO <> [cache2k] Cache{newsArchiveCache}(size=1000, maxSize=1000, usageCnt=9176, missCnt=3350, fetchCnt=6941, fetchButHitCnt=4187, heapHitCnt=6422, virginEvictCnt=0, fetchesInFlightCnt=0, newEntryCnt=2754, bulkGetCnt=0, refreshCnt=3591, refreshSubmitFailedCnt=30, refreshHitCnt=911, putCnt=0, putNewEntryCnt=0, expiredCnt=3264, evictedCnt=1754, removedCnt=0, storageLoadCnt=0, storageMissCnt=0, storageHitCnt=0, hitRate=63.49%, collisionCnt=199, collisionSlotCnt=169, longestCollisionSize=5, hashQuality=83, msecs/fetch=88.58867598328771, created=2015-06-13 07:32:33.12, cleared=-, touched=2015-06-13 09:32:53.006, fetchExceptionCnt=3636, suppressedExceptionCnt=3598, internalExceptionCnt=0, keyMutationCnt=0, infoCreated=2015-06-13 09:32:53.376, infoCreationDeltaMs=0, impl="LruCache", integrityState=0.9.4f79b249)
2015-06-13 09:42:53,391 INFO <> [cache2k] Cache{newsArchiveCache}(size=1000, maxSize=1000, usageCnt=9606, missCnt=3663, fetchCnt=7606, fetchButHitCnt=4620, heapHitCnt=6620, virginEvictCnt=0, fetchesInFlightCnt=0, newEntryCnt=2986, bulkGetCnt=0, refreshCnt=3943, refreshSubmitFailedCnt=30, refreshHitCnt=1020, putCnt=0, putNewEntryCnt=0, expiredCnt=3598, evictedCnt=1986, removedCnt=0, storageLoadCnt=0, storageMissCnt=0, storageHitCnt=0, hitRate=61.86%, collisionCnt=201, collisionSlotCnt=173, longestCollisionSize=4, hashQuality=88, msecs/fetch=83.16815671838023, created=2015-06-13 07:32:33.12, cleared=-, touched=2015-06-13 09:42:52.975, fetchExceptionCnt=3988, suppressedExceptionCnt=3950, internalExceptionCnt=0, keyMutationCnt=0, infoCreated=2015-06-13 09:42:53.391, infoCreationDeltaMs=0, impl="LruCache", integrityState=0.9.4f79b249)
2015-06-13 09:52:54,739 INFO <> [cache2k] Cache{newsArchiveCache}(size=1000, maxSize=1000, usageCnt=10035, missCnt=3952, fetchCnt=8207, fetchButHitCnt=4996, heapHitCnt=6824, virginEvictCnt=0, fetchesInFlightCnt=0, newEntryCnt=3211, bulkGetCnt=0, refreshCnt=4255, refreshSubmitFailedCnt=30, refreshHitCnt=1117, putCnt=0, putNewEntryCnt=0, expiredCnt=3874, evictedCnt=2211, removedCnt=0, storageLoadCnt=0, storageMissCnt=0, storageHitCnt=0, hitRate=60.61%, collisionCnt=200, collisionSlotCnt=165, longestCollisionSize=4, hashQuality=88, msecs/fetch=79.21847203606677, created=2015-06-13 07:32:33.12, cleared=-, touched=2015-06-13 09:52:54.59, fetchExceptionCnt=4300, suppressedExceptionCnt=4262, internalExceptionCnt=0, keyMutationCnt=0, infoCreated=2015-06-13 09:52:54.739, infoCreationDeltaMs=0, impl="LruCache", integrityState=0.9.4f79b249)
2015-06-13 10:02:56,938 INFO <> [cache2k] Cache{newsArchiveCache}(size=1000, maxSize=1000, usageCnt=10591, missCnt=4371, fetchCnt=9096, fetchButHitCnt=5538, heapHitCnt=7033, virginEvictCnt=0, fetchesInFlightCnt=0, newEntryCnt=3558, bulkGetCnt=0, refreshCnt=4725, refreshSubmitFailedCnt=30, refreshHitCnt=1226, putCnt=0, putNewEntryCnt=0, expiredCnt=4303, evictedCnt=2558, removedCnt=0, storageLoadCnt=0, storageMissCnt=0, storageHitCnt=0, hitRate=58.72%, collisionCnt=197, collisionSlotCnt=160, longestCollisionSize=5, hashQuality=83, msecs/fetch=74.31442392260334, created=2015-06-13 07:32:33.12, cleared=-, touched=2015-06-13 10:02:56.447, fetchExceptionCnt=4770, suppressedExceptionCnt=4732, internalExceptionCnt=0, keyMutationCnt=0, infoCreated=2015-06-13 10:02:56.938, infoCreationDeltaMs=0, impl="LruCache", integrityState=0.9.4f79b249)
2015-06-13 10:12:57,366 INFO <> [cache2k] Cache{newsArchiveCache}(size=1000, maxSize=1000, usageCnt=11082, missCnt=4718, fetchCnt=9823, fetchButHitCnt=6001, heapHitCnt=7260, virginEvictCnt=0, fetchesInFlightCnt=0, newEntryCnt=3822, bulkGetCnt=0, refreshCnt=5105, refreshSubmitFailedCnt=30, refreshHitCnt=1348, putCnt=0, putNewEntryCnt=0, expiredCnt=4646, evictedCnt=2822, removedCnt=0, storageLoadCnt=0, storageMissCnt=0, storageHitCnt=0, hitRate=57.42%, collisionCnt=192, collisionSlotCnt=158, longestCollisionSize=5, hashQuality=83, msecs/fetch=71.2268146187519, created=2015-06-13 07:32:33.12, cleared=-, touched=2015-06-13 10:12:56.471, fetchExceptionCnt=5150, suppressedExceptionCnt=5112, internalExceptionCnt=0, keyMutationCnt=0, infoCreated=2015-06-13 10:12:57.366, infoCreationDeltaMs=0, impl="LruCache", integrityState=0.9.4f79b249)
2015-06-13 10:22:59,968 INFO <> [cache2k] Cache{newsArchiveCache}(size=1000, maxSize=1000, usageCnt=11551, missCnt=5061, fetchCnt=10557, fetchButHitCnt=6465, heapHitCnt=7459, virginEvictCnt=0, fetchesInFlightCnt=0, newEntryCnt=4092, bulkGetCnt=0, refreshCnt=5496, refreshSubmitFailedCnt=30, refreshHitCnt=1459, putCnt=0, putNewEntryCnt=0, expiredCnt=5000, evictedCnt=3092, removedCnt=0, storageLoadCnt=0, storageMissCnt=0, storageHitCnt=0, hitRate=56.18%, collisionCnt=198, collisionSlotCnt=171, longestCollisionSize=4, hashQuality=88, msecs/fetch=68.42256322818983, created=2015-06-13 07:32:33.12, cleared=-, touched=2015-06-13 10:22:59.867, fetchExceptionCnt=5541, suppressedExceptionCnt=5503, internalExceptionCnt=0, keyMutationCnt=0, infoCreated=2015-06-13 10:22:59.968, infoCreationDeltaMs=0, impl="LruCache", integrityState=0.9.4f79b249)
```

**Comment by cruftex** [comment] 2015-06-13 20:04
Very interesting. From the last line I'd picked the suspicious values:

fetchCnt=10557
fetchExceptionCnt=5541
suppressedExceptionCnt=5503

There is a high amount of exceptions. The problem could be related to the suppress exceptions code in the cache. I will do a review and check it.

The number of exceptions is very suspicious. Exceptions seam not to be very exceptional ;) Maybe something is causing the CacheSource code constantly to fail and throw exceptions?

**Comment by cruftex** [comment] 2015-06-13 20:07
Another hint: Exceptions by default have an expiry of 1/10 of the normal expiry time. This, means in your case, as soon as an exception happens, the cache will retry to fetch the value from the source (since background refresh) in 6 seconds.

**Comment by cruftex** [comment] 2015-06-13 20:39
Just checked, that the reduced expiry also is applied correctly, when an exception is suppressed. Caching and suppressing exceptions is a cool feature, but debugging is hell, since you do not know what goes on under the hood.

Spontaneous ideas to improve the exception caching mechanism:
- metrics for total amount of cache entries that have exceptions and the cached entries that are expired, but work with old values because exceptions are suppressed
- the last 3 suppressed exceptions from the cache source (to look under the hood)
- SuppressedExceptionQualifier: suppressing exceptions in general means that general programming problems might get undetected. Some exceptions like NPE or IllegalArgumentException should not be cached.

**Comment by mohsen** [comment] 2015-06-14 06:52
This special cache, newsArchiveCacne, (I have 10+ instances of cache for different parts) in my app is very exceptional and the number of exceptions thrown is correct. There is an issue with some user queries which I'm trying to fix but still exists.

For the case of exception expiry timeout, I manually set it same as expiry duration. So
cache.expiryDuration and cache.exceptionExpiryDuration are both set to 1 minute. In exceptional cases, there is no data available in the cache so that cache2k can return it. Actually exceptional cases are those queries with some sort of SQL errors which never lead to a sound result.

What happens when a cache load result into an exception with no old value for this key?

**Comment by cruftex** [comment] 2015-06-14 15:45
> What happens when a cache load result into an exception with no old value for this key, i.e., this special key would never has a value in the cache?

The exception will get propagated, wrapped into a PropagatedCacheException.

**Comment by cruftex** [comment] 2015-06-14 18:25
Questions regarding the "stuck entry":
- Did this entry / key, had one or more exceptions?
- How often is the entry fetched successfully?
- Is it only one or a subset of the keys within one cache instance that have this behaviour, or is it the whole cache, that does no updates any more?
- The effect is the same without backgroundRefresh?
- How differs the code from how you use Google Guava?

I think it would also be good to do some tracing in the cache source:

- print out that a key is requested
- print out when success
- print out the exception

To make sure that the value is really not requested by the cache and the problem source is not the exceptions.

**Comment by mohsen** [comment] 2015-06-15 12:57
1. Exceptions are more than one in that special real-testing (all wrapped in ``PropagatedCacheException``). There was a connection lacking issue that day. We usually have these exceptions:
  * ``org.springframework.jdbc.UncategorizedSQLException``
  * ``org.springframework.transaction.CannotCreateTransactionException``
  * ``org.springframework.dao.CannotAcquireLockException``
-- But in that test almost 99% of exceptions was ``org.springframework.transaction.CannotCreateTransactionException`` because of ``org.hibernate.exception.GenericJDBCException: Could not open connection``

2. Over 99% of exceptions happened in a connection starvation issue in less than a minute, but after that we had and exceptions every 7-8 minutes.

3. I had this issue for several different cache keys. The one I reported here is the most complex one with about 10 fields. But eternal caching already happened for simpler keys as well.

4. I doubt. I only used backgroundRefresh in this test. Before that I didn't know about that property, so eternal caching occurred every one week. This time it happened after 2-3 hours of startup.

5. Here is how I build guava:
```
    private <K, V> LoadingCache<K, V> buildGuava(String cacheName, final Loader<K, V> loader, Integer expireAfterSeconds,
            TimeUnit timeUnit, int maxSize) {
        if (expireAfterSeconds != null) {
            return CacheBuilder.newBuilder()
                    .maximumSize(maxSize)
                    .expireAfterWrite(expireAfterSeconds, timeUnit)
                    .build(new CacheLoader<K, V>() {
                        public V load(K key) {
                            return loader.load(key);
                        }
                    });
        } else {
            return CacheBuilder.newBuilder()
                    .maximumSize(maxSize)
                    .build(new CacheLoader<K, V>() {
                        public V load(K key) {
                            return loader.load(key);
                        }
                    });
        }
    }
```
6. OK I'll give it a try.

**Comment by cruftex** [comment] 2015-07-11 22:34
I was travelling and away from the internet and busy with other stuff in the meantime. However, I was able to do some additional testing around caching, expiry and exceptions. The general functionality looks okay to me.

Do you have any new findings? Should we continue to work on the resolution?

My next idea would be to provide a new cache2k version which has more debugging/statistics support, so we may have better indicators to pinpoint the problem.

**Comment by mohsen** [comment] 2015-07-12 07:15
Please keep this issue open and I'll report new findings as soon as I can test it against my high traffic website.

**Comment by cruftex** [comment] 2015-07-29 01:31
I can confirm now that version 0.21 has an issue with not expiring entries correctly. However, this issue is triggered when an entry is inserted and the expiry time is in the area of 666 milliseconds.

I will make a bug fix release in the next days and give some further information.

**Comment by mohsen** [comment] 2015-07-29 01:43
Thank you very much for having an eye on this issue. My expiry times are at least 30 secs, but since I cache a lot of data and JVM soon reaches its 14GB memory limit, it it's possible that a cache is expired sooner (within that 666ms range), because of the nature of soft references used by LRU caches. Am I right?

**Comment by cruftex** [comment] 2015-07-29 02:36
cache2k does not use soft or weak references. Google Guava supports this. I don't like the approach, because the GC will throw out any object if it thinks it needs the memory. However, in a cache we want to evict the entry that is probably not used in the future any more. Further more soft and weak references consume memory and cost CPU cycles at access.

The good thing of soft and weak references in the cache is that it keeps your memory in defined boundaries, without the admin needing to do any thing. However, the cache and the GC will work against each other: The cache will put new objects into the heap and the GC will throw them out again. The better option is to reduce the cache size.

That said, I am aware of the fact that it is impractical to tune the size for every cache. EHCache with ARC has an interesting approach for this. This area needs more thoughts in the future....

Some more explanation about the problem:

cache2k uses a timer event to expire the entries. Other caches typically check the time on every access and return the object if the time has not reached. Using a timer has advantages and disadvantages.

Disadvantages:

- The timer event consumes memory
- Updating the timer data structures is not possible in constant time. It is a priority queue, inserting is O(log n)
- Expiring may lag a few milliseconds
- Currently we need one timer thread per cache. This is bad in environments with lower resources, like Android
- The code is quite complex since the timer has to be updated correctly :(

Advantage:

- Access to a cache entry is blazing fast, since no additional time check is needed

BTW: The lagging problem is solved with the sharpExpiry parameter. In this case a timer event is used and before 666 milliseconds of the anticipated expiry cache2k switches back to checking the time at every request.

If the root cause is a bug in cache2k, your problem may be triggered either due to a failure updating the timer or executing the timer event or the timer thread died completely and no timer event are executed at all. Question: Is one cache completely affected or is it one or only a few values?

**Comment by cruftex** [comment] 2015-07-29 02:50
I will provide a mechanism to switch off the timer usage completely, so we can easily check whether this could be the problem source.

**Comment by mohsen** [comment] 2015-07-29 04:52
To answer your question, only one entry of a cache was affected. Usually the entry shown on homepage which is most frequently fetched.

**Comment by mohsen** [comment] 2015-09-11 05:50
Again a test case in that high-traffic website. It's generated using cache2k 0.21.0. As I understood there is not difference between 0.21.1 and 0.21.0 in my case, and there is no newer release yet.

I started my app at 10:14 with several fixed time caches, one of them which is highly accessed (newsArchiveCache, refreshed every 1 min) cached an item at about 10:36. That item was not refreshed again until I disabled cache2k at about 12:00. Here are cache iternals:

[application startup with cache2k]

```
2015-09-08 10:14:51,779 INFO <> [cache2k] Cache{newsArchiveCache}(size=0, maxSize=5000, usageCnt=0, missCnt=0, fetchCnt=0, fetchButHitCnt=0, heapHitCnt=0, virginEvictCnt=0, fetchesInFlightCnt=0, newEntryCnt=0, bulkGetCnt=0, refreshCnt=0, refreshSubmitFailedCnt=0, refreshHitCnt=0, putCnt=0, putNewEntryCnt=0, expiredCnt=0, evictedCnt=0, removedCnt=0, storageLoadCnt=0, storageMissCnt=0, storageHitCnt=0, hitRate=100.0%, collisionCnt=0, collisionSlotCnt=0, longestCollisionSize=0, hashQuality=100, msecs/fetch=-, created=2015-09-08 10:14:48.253, cleared=-, touched=-, fetchExceptionCnt=0, suppressedExceptionCnt=0, internalExceptionCnt=0, keyMutationCnt=0, infoCreated=2015-09-08 10:14:51.779, infoCreationDeltaMs=0, impl="LruCache", integrityState=0.9.4f79b249)

2015-09-08 10:24:51,792 INFO <> [cache2k] Cache{newsArchiveCache}(size=1650, maxSize=5000, usageCnt=4005, missCnt=1695, fetchCnt=3245, fetchButHitCnt=1596, heapHitCnt=2355, virginEvictCnt=0, fetchesInFlightCnt=1, newEntryCnt=1650, bulkGetCnt=0, refreshCnt=1550, refreshSubmitFailedCnt=14, refreshHitCnt=94, putCnt=0, putNewEntryCnt=0, expiredCnt=1346, evictedCnt=0, removedCnt=0, storageLoadCnt=0, storageMissCnt=0, storageHitCnt=0, hitRate=57.67%, collisionCnt=262, collisionSlotCnt=226, longestCollisionSize=4, hashQuality=88, msecs/fetch=169.79229583975348, created=2015-09-08 10:14:48.253, cleared=-, touched=2015-09-08 10:24:51.723, fetchExceptionCnt=1550, suppressedExceptionCnt=1544, internalExceptionCnt=0, keyMutationCnt=0, infoCreated=2015-09-08 10:24:51.791, infoCreationDeltaMs=1, impl="LruCache", integrityState=0.9.4f79b249)

2015-09-08 10:34:51,825 INFO <> [cache2k] Cache{newsArchiveCache}(size=3343, maxSize=5000, usageCnt=8156, missCnt=3504, fetchCnt=6928, fetchButHitCnt=3585, heapHitCnt=4813, virginEvictCnt=0, fetchesInFlightCnt=0, newEntryCnt=3343, bulkGetCnt=0, refreshCnt=3424, refreshSubmitFailedCnt=17, refreshHitCnt=262, putCnt=0, putNewEntryCnt=0, expiredCnt=3149, evictedCnt=0, removedCnt=0, storageLoadCnt=0, storageMissCnt=0, storageHitCnt=0, hitRate=57.03%, collisionCnt=591, collisionSlotCnt=513, longestCollisionSize=4, hashQuality=88, msecs/fetch=105.97459584295612, created=2015-09-08 10:14:48.253, cleared=-, touched=2015-09-08 10:34:51.705, fetchExceptionCnt=3424, suppressedExceptionCnt=3418, internalExceptionCnt=0, keyMutationCnt=0, infoCreated=2015-09-08 10:34:51.824, infoCreationDeltaMs=1, impl="LruCache", integrityState=0.9.4f79b249)

2015-09-08 10:44:52,155 INFO <> [cache2k] Cache{newsArchiveCache}(size=5000, maxSize=5000, usageCnt=12459, missCnt=5387, fetchCnt=10736, fetchButHitCnt=5668, heapHitCnt=7391, virginEvictCnt=0, fetchesInFlightCnt=0, newEntryCnt=5068, bulkGetCnt=0, refreshCnt=5349, refreshSubmitFailedCnt=20, refreshHitCnt=475, putCnt=0, putNewEntryCnt=0, expiredCnt=5007, evictedCnt=68, removedCnt=0, storageLoadCnt=0, storageMissCnt=0, storageHitCnt=0, hitRate=56.76%, collisionCnt=1226, collisionSlotCnt=992, longestCollisionSize=5, hashQuality=83, msecs/fetch=85.03045827123697, created=2015-09-08 10:14:48.253, cleared=-, touched=2015-09-08 10:44:51.974, fetchExceptionCnt=5315, suppressedExceptionCnt=5309, internalExceptionCnt=0, keyMutationCnt=0, infoCreated=2015-09-08 10:44:52.153, infoCreationDeltaMs=1, impl="LruCache", integrityState=0.9.4f79b249)

2015-09-08 10:54:52,186 INFO <> [cache2k] Cache{newsArchiveCache}(size=5000, maxSize=5000, usageCnt=16823, missCnt=7211, fetchCnt=14425, fetchButHitCnt=7723, heapHitCnt=10121, virginEvictCnt=0, fetchesInFlightCnt=0, newEntryCnt=6702, bulkGetCnt=0, refreshCnt=7214, refreshSubmitFailedCnt=20, refreshHitCnt=736, putCnt=0, putNewEntryCnt=0, expiredCnt=6838, evictedCnt=1702, removedCnt=0, storageLoadCnt=0, storageMissCnt=0, storageHitCnt=0, hitRate=57.13%, collisionCnt=1239, collisionSlotCnt=1017, longestCollisionSize=5, hashQuality=83, msecs/fetch=77.62703639514731, created=2015-09-08 10:14:48.253, cleared=-, touched=2015-09-08 10:54:52.184, fetchExceptionCnt=7171, suppressedExceptionCnt=7165, internalExceptionCnt=0, keyMutationCnt=0, infoCreated=2015-09-08 10:54:52.185, infoCreationDeltaMs=1, impl="LruCache", integrityState=0.9.4f79b249)

2015-09-08 11:04:52,471 INFO <> [cache2k] Cache{newsArchiveCache}(size=5000, maxSize=5000, usageCnt=21176, missCnt=8998, fetchCnt=18071, fetchButHitCnt=9777, heapHitCnt=12882, virginEvictCnt=0, fetchesInFlightCnt=0, newEntryCnt=8294, bulkGetCnt=0, refreshCnt=9073, refreshSubmitFailedCnt=20, refreshHitCnt=976, putCnt=0, putNewEntryCnt=0, expiredCnt=8634, evictedCnt=3294, removedCnt=0, storageLoadCnt=0, storageMissCnt=0, storageHitCnt=0, hitRate=57.50%, collisionCnt=1230, collisionSlotCnt=1016, longestCollisionSize=5, hashQuality=83, msecs/fetch=74.03093353992585, created=2015-09-08 10:14:48.253, cleared=-, touched=2015-09-08 11:04:52.092, fetchExceptionCnt=9029, suppressedExceptionCnt=9023, internalExceptionCnt=0, keyMutationCnt=0, infoCreated=2015-09-08 11:04:52.47, infoCreationDeltaMs=0, impl="LruCache", integrityState=0.9.4f79b249)

2015-09-08 11:14:52,654 INFO <> [cache2k] Cache{newsArchiveCache}(size=5000, maxSize=5000, usageCnt=25485, missCnt=10732, fetchCnt=21636, fetchButHitCnt=11773, heapHitCnt=15622, virginEvictCnt=0, fetchesInFlightCnt=0, newEntryCnt=9863, bulkGetCnt=0, refreshCnt=10904, refreshSubmitFailedCnt=23, refreshHitCnt=1219, putCnt=0, putNewEntryCnt=0, expiredCnt=10390, evictedCnt=4863, removedCnt=0, storageLoadCnt=0, storageMissCnt=0, storageHitCnt=0, hitRate=57.88%, collisionCnt=1207, collisionSlotCnt=1007, longestCollisionSize=5, hashQuality=83, msecs/fetch=73.25032353484933, created=2015-09-08 10:14:48.253, cleared=-, touched=2015-09-08 11:14:52.473, fetchExceptionCnt=10860, suppressedExceptionCnt=10854, internalExceptionCnt=0, keyMutationCnt=0, infoCreated=2015-09-08 11:14:52.653, infoCreationDeltaMs=1, impl="LruCache", integrityState=0.9.4f79b249)

2015-09-08 11:24:52,714 INFO <> [cache2k] Cache{newsArchiveCache}(size=5000, maxSize=5000, usageCnt=29830, missCnt=12513, fetchCnt=25205, fetchButHitCnt=13745, heapHitCnt=18370, virginEvictCnt=0, fetchesInFlightCnt=0, newEntryCnt=11460, bulkGetCnt=0, refreshCnt=12692, refreshSubmitFailedCnt=33, refreshHitCnt=1461, putCnt=0, putNewEntryCnt=0, expiredCnt=12140, evictedCnt=6460, removedCnt=0, storageLoadCnt=0, storageMissCnt=0, storageHitCnt=0, hitRate=58.05%, collisionCnt=1155, collisionSlotCnt=969, longestCollisionSize=5, hashQuality=83, msecs/fetch=70.29291807181114, created=2015-09-08 10:14:48.253, cleared=-, touched=2015-09-08 11:24:52.559, fetchExceptionCnt=12648, suppressedExceptionCnt=12642, internalExceptionCnt=0, keyMutationCnt=0, infoCreated=2015-09-08 11:24:52.713, infoCreationDeltaMs=1, impl="LruCache", integrityState=0.9.4f79b249)

2015-09-08 11:34:52,767 INFO <> [cache2k] Cache{newsArchiveCache}(size=5000, maxSize=5000, usageCnt=34178, missCnt=14255, fetchCnt=28800, fetchButHitCnt=15785, heapHitCnt=21163, virginEvictCnt=0, fetchesInFlightCnt=0, newEntryCnt=13015, bulkGetCnt=0, refreshCnt=14545, refreshSubmitFailedCnt=35, refreshHitCnt=1705, putCnt=0, putNewEntryCnt=0, expiredCnt=13921, evictedCnt=8015, removedCnt=0, storageLoadCnt=0, storageMissCnt=0, storageHitCnt=0, hitRate=58.29%, collisionCnt=1213, collisionSlotCnt=979, longestCollisionSize=6, hashQuality=78, msecs/fetch=67.22552083333333, created=2015-09-08 10:14:48.253, cleared=-, touched=2015-09-08 11:34:52.5, fetchExceptionCnt=14501, suppressedExceptionCnt=14495, internalExceptionCnt=0, keyMutationCnt=0, infoCreated=2015-09-08 11:34:52.767, infoCreationDeltaMs=0, impl="LruCache", integrityState=0.9.4f79b249)

2015-09-08 11:44:52,821 INFO <> [cache2k] Cache{newsArchiveCache}(size=5000, maxSize=5000, usageCnt=38546, missCnt=16127, fetchCnt=32543, fetchButHitCnt=17839, heapHitCnt=23842, virginEvictCnt=0, fetchesInFlightCnt=0, newEntryCnt=14704, bulkGetCnt=0, refreshCnt=16416, refreshSubmitFailedCnt=35, refreshHitCnt=1933, putCnt=0, putNewEntryCnt=0, expiredCnt=15759, evictedCnt=9704, removedCnt=0, storageLoadCnt=0, storageMissCnt=0, storageHitCnt=0, hitRate=58.16%, collisionCnt=1286, collisionSlotCnt=1048, longestCollisionSize=6, hashQuality=78, msecs/fetch=65.0452324616661, created=2015-09-08 10:14:48.253, cleared=-, touched=2015-09-08 11:44:52.605, fetchExceptionCnt=16357, suppressedExceptionCnt=16351, internalExceptionCnt=0, keyMutationCnt=0, infoCreated=2015-09-08 11:44:52.82, infoCreationDeltaMs=1, impl="LruCache", integrityState=0.9.4f79b249)

2015-09-08 11:54:53,326 INFO <> [cache2k] Cache{newsArchiveCache}(size=5000, maxSize=5000, usageCnt=42996, missCnt=17985, fetchCnt=36319, fetchButHitCnt=19921, heapHitCnt=26598, virginEvictCnt=0, fetchesInFlightCnt=0, newEntryCnt=16398, bulkGetCnt=0, refreshCnt=18334, refreshSubmitFailedCnt=40, refreshHitCnt=2145, putCnt=0, putNewEntryCnt=0, expiredCnt=17645, evictedCnt=11398, removedCnt=0, storageLoadCnt=0, storageMissCnt=0, storageHitCnt=0, hitRate=58.17%, collisionCnt=1265, collisionSlotCnt=1041, longestCollisionSize=5, hashQuality=83, msecs/fetch=64.24463779289077, created=2015-09-08 10:14:48.253, cleared=-, touched=2015-09-08 11:54:52.377, fetchExceptionCnt=18273, suppressedExceptionCnt=18267, internalExceptionCnt=0, keyMutationCnt=0, infoCreated=2015-09-08 11:54:53.325, infoCreationDeltaMs=1, impl="LruCache", integrityState=0.9.4f79b249)
```

**Comment by cruftex** [comment] 2016-01-04 16:39
The version 0.22 contained a fix in this area, see change log: http://cache2k.org/0/22.html

I did some intensive studying in our productions systems, none seams to be affected.
After some further testing under high load scenarios, I found another issue that leads to the described behavior: If the expiry calculator returns a time near the current time or already in the past, and, when background refresh is enabled.

Will release this as 0.22.1.

**Comment by cruftex** [comment] 2016-02-10 15:51
Closing this now. I think it is thoroughly investigated, towards potential bugs in cache2k.

I think, as mentioned above, we may need more support in cache2k for better debugging information in case there are a lot of exceptions. For this, I opened another issue:

https://github.com/cache2k/cache2k/issues/26

**Closed by cruftex** 2016-02-10 15:51 UTC
Labels: bug, question
